export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="ys"

HIST_STAMPS="yyyy/mm/dd"

plugins=(git)

source $ZSH/oh-my-zsh.sh

export LANG=en_US.UTF-8

export PATH=$HOME/bin:/usr/local/bin:/usr/bin:/usr/sbin:/usr/local/sbin:/bin

if [ -d $HOME/.shrc.d ]; then
  for file in $HOME/.shrc.d/*; do
    source $file
  done
fi
